/*
 Copyright (c) 2026 Fran6nd, ZeroSpades developers.

 This file is part of ZeroSpades, a fork of OpenSpades.

 ZeroSpades is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 ZeroSpades is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with ZeroSpades.  If not, see <http://www.gnu.org/licenses/>.

 */

// The horizontal half of the colour correction's sharpening blur (GL's Gauss1D
// over ColorCorrection.fs's input), in the encoded space that pass works in: the
// input is linear here, so it is encoded first, as ColorCorrection.vk.fs encodes
// it. The vertical half is done there, as it samples this. Pair with
// PassThrough.vk.vs.

#version 450

layout(binding = 0) uniform sampler2D sceneTexture;

layout(push_constant) uniform Params {
	// The step between texels along the blur
	vec2 unitShift;
	// 1 when the input is sRGB-decoded (r_hdr), 0 when it is squared
	float useHdr;
} params;

layout(location = 0) in vec2 texCoord;
layout(location = 0) out vec4 outColor;

vec3 linearToSrgb(vec3 c) {
	bvec3 lo = lessThanEqual(c, vec3(0.0031308));
	vec3 sLo = c * 12.92;
	vec3 sHi = 1.055 * pow(c, vec3(1.0 / 2.4)) - 0.055;
	return mix(sHi, sLo, vec3(lo));
}

vec3 Encoded(vec2 coord) {
	vec3 color = max(texture(sceneTexture, coord).rgb, 0.0);
	return params.useHdr > 0.5 ? linearToSrgb(color) : sqrt(color);
}

void main() {
	// generated by ./1dgaussGen.rb, as GL's Gauss1D
	vec2 s1 = params.unitShift * 2.30654399138844;
	vec2 s2 = params.unitShift * 0.629455560633963;
	const float w1 = 0.178704407070903;
	const float w2 = 0.321295592929097;

	vec3 blurred = Encoded(texCoord - s1) * w1;
	blurred += Encoded(texCoord - s2) * w2;
	blurred += Encoded(texCoord + s2) * w2;
	blurred += Encoded(texCoord + s1) * w1;
	outColor = vec4(blurred, 1.0);
}
