/*
 Copyright (c) 2013 Fran6nd

 This file is part of ZeroSpades, a fork of OpenSpades.

 OpenSpades is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 OpenSpades is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with OpenSpades.  If not, see <http://www.gnu.org/licenses/>.

 */

// 1D Gaussian blur fragment shader for single-channel CoC images.
// Port of OpenGL/PostFilters/Gauss1D.fs/.vs.
//
// Four-tap separable Gaussian (sigma ~= 1).  Run twice: once with
// unitShift = (spread/width, 0) and once with (0, spread/height).
//
// Descriptor set layout (set 0):
//   binding 0 — mainTexture (sampler2D, R8 single-channel CoC image)

#version 450

layout(binding = 0) uniform sampler2D mainTexture;

layout(push_constant) uniform Params {
    vec2 unitShift; // per-pixel shift in texture-coordinate space
} pc;

layout(location = 0) in  vec2 texCoord;
layout(location = 0) out float outCoC;

void main() {
    // Generated by the original 1dgaussGen.rb script.
    const float shift1 = -2.30654399138844;
    const float scale1 =  0.178704407070903;
    const float shift2 = -0.629455560633963;
    const float scale2 =  0.321295592929097;
    const float shift3 =  0.629455560633963;
    const float scale3 =  0.321295592929097;
    const float shift4 =  2.30654399138844;
    const float scale4 =  0.178704407070903;

    outCoC  = texture(mainTexture, texCoord + pc.unitShift * shift1).r * scale1;
    outCoC += texture(mainTexture, texCoord + pc.unitShift * shift2).r * scale2;
    outCoC += texture(mainTexture, texCoord + pc.unitShift * shift3).r * scale3;
    outCoC += texture(mainTexture, texCoord + pc.unitShift * shift4).r * scale4;
}
