/*
 Copyright (c) 2026 Fran6nd, ZeroSpades developers.

 This file is part of ZeroSpades, a fork of OpenSpades.

 OpenSpades is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 OpenSpades is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with OpenSpades.  If not, see <http://www.gnu.org/licenses/>.

 */

// RGBA 4-tap separable 1D Gaussian (sigma ≈ 1).  Used by the lens
// flare filter to blur the 64×64 visibility buffer three times
// (spread = 1, 2, 4).  Run once with unitShift = (spread/w, 0) and
// once with (0, spread/h).
//
// Constants generated by the original 1dgaussGen.rb script.

#version 450

layout(binding = 0) uniform sampler2D mainTexture;

layout(push_constant) uniform Params {
    vec2 unitShift; // per-pixel shift in texture-coordinate space
} pc;

layout(location = 0) in  vec2 texCoord;
layout(location = 0) out vec4 outColor;

void main() {
    const float s1 = -2.30654399138844;
    const float w1 =  0.178704407070903;
    const float s2 = -0.629455560633963;
    const float w2 =  0.321295592929097;
    const float s3 =  0.629455560633963;
    const float w3 =  0.321295592929097;
    const float s4 =  2.30654399138844;
    const float w4 =  0.178704407070903;

    outColor  = texture(mainTexture, texCoord + pc.unitShift * s1) * w1;
    outColor += texture(mainTexture, texCoord + pc.unitShift * s2) * w2;
    outColor += texture(mainTexture, texCoord + pc.unitShift * s3) * w3;
    outColor += texture(mainTexture, texCoord + pc.unitShift * s4) * w4;
}
